[features]
seeds = false
skip-lint = false
#[programs.devnet]
#joint_market = ""

[programs.mainnet]
joint_market = ""

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "a"
wallet = "./programAuth.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[dependencies]
solana-program = "1.14.20"